const ProjectListData = [
  {
    id: 27,
    name: "nitesh_n",
    category: "Site Page Design",
    platform: "Upwork",
    attachmentCount: 12,
    totalTask: 32,
    client: "Mark Kelso",
    completedTask: 27,
    progression: 80,
    dayleft: 21,
    date: "22-05-2000",
    statusColor: "none",
    member: [
      {
        name: "Frederick Adams",
        img: "/img/avatars/thumb-8.jpg",
        avatarColor: "",
      },
      {
        name: "Joyce Freeman",
        img: "/img/avatars/thumb-5.jpg",
        avatarColor: "",
      },
      {
        name: "Clayton Bates",
        img: "",
        avatarColor: "cyan",
      },
      {
        name: "Clayton Bates",
        img: "",
        avatarColor: "cyan",
      },
    ],
  },
  {
    id: 28,
    name: "nitesh_n",
    category: "Mobile Application",
    platform: "Upwork",
    attachmentCount: 5,
    totalTask: 36,
    client: "Mark Kelso",
    date: "22-05-2000",
    completedTask: 15,
    progression: 45,
    dayleft: 19,
    statusColor: "none",
    member: [
      {
        name: "Eileen Horton",
        img: "/img/avatars/thumb-1.jpg",
        avatarColor: "",
      },
      {
        name: "Gabriel Frazier",
        img: "",
        avatarColor: "blue",
      },
    ],
  },
  {
    id: 29,
    name: "nitesh_n",
    category: "Web Backend Application",
    platform: "Upwork",
    attachmentCount: 8,
    totalTask: 27,
    completedTask: 19,
    date: "22-05-2000",
    client: "Mark Kelso",
    progression: 73,
    dayleft: 6,
    statusColor: "orange",
    member: [
      {
        name: "Debra Hamilton",
        img: "",
        avatarColor: "gold",
      },
      {
        name: "Stacey Ward",
        img: "",
        avatarColor: "purple",
      },
      {
        name: "Ron Vargas",
        img: "/img/avatars/thumb-3.jpg",
        avatarColor: "",
      },
      {
        name: "Ron Vargas",
        img: "/img/avatars/thumb-3.jpg",
        avatarColor: "",
      },
      {
        name: "Ron Vargas",
        img: "/img/avatars/thumb-3.jpg",
        avatarColor: "",
      },
      {
        name: "Ron Vargas",
        img: "/img/avatars/thumb-3.jpg",
        avatarColor: "",
      },
    ],
  },
  {
    id: 30,
    name: "nitesh_n",
    category: "Backend Services",
    platform: "Upwork",
    attachmentCount: 2,
    totalTask: 15,
    date: "22-05-2000",
    completedTask: 13,
    client: "Mark Kelso",
    progression: 87,
    dayleft: 2,
    statusColor: "red",
    member: [
      {
        name: "Troy Alexander",
        img: "",
        avatarColor: "red",
      },
      {
        name: "Lloyd Obrien",
        img: "/img/avatars/thumb-11.jpg",
        avatarColor: "",
      },
    ],
  },
  {
    id: 31,
    name: "nitesh_n",
    category: "Backend Application",
    attachmentCount: 8,
    totalTask: 78,
    completedTask: 23,
    date: "22-05-2000",
    platform: "Upwork",
    client: "Mark Kelso",
    progression: 21,
    dayleft: 52,
    statusColor: "cyan",
    member: [
      {
        name: "Brittany Hale",
        img: "/img/avatars/thumb-10.jpg",
        avatarColor: "",
      },
      {
        name: "Frederick Adams",
        img: "/img/avatars/thumb-8.jpg",
        avatarColor: "",
      },
      {
        name: "Samantha Phillips",
        img: "/img/avatars/thumb-6.jpg",
        avatarColor: "",
      },
      {
        name: "Samantha Phillips",
        img: "/img/avatars/thumb-6.jpg",
        avatarColor: "",
      },
      {
        name: "Samantha Phillips",
        img: "/img/avatars/thumb-6.jpg",
        avatarColor: "",
      },
    ],
  },
  {
    id: 32,
    name: "nitesh_n",
    category: "Frontend Web Application",
    attachmentCount: 6,
    totalTask: 18,
    platform: "Upwork",
    completedTask: 9,
    progression: 50,
    client: "Mark Kelso",
    date: "22-05-2000",
    dayleft: 6,
    statusColor: "orange",
    member: [
      {
        name: "Gabriella May",
        img: "/img/avatars/thumb-12.jpg",
        avatarColor: "",
      },
      {
        name: "Larry Campbell",
        img: "",
        avatarColor: "blue",
      },
      {
        name: "Phyllis Chapman",
        img: "",
        avatarColor: "gold",
      },
    ],
  },
  {
    id: 33,
    name: "nitesh_n",
    category: "Mobile Application",
    attachmentCount: 3,
    totalTask: 26,
    completedTask: 19,
    date: "22-05-2000",
    client: "Mark Kelso",
    platform: "Upwork",
    progression: 67,
    dayleft: 14,
    statusColor: "none",
    member: [
      {
        name: "Lee Wheeler",
        img: "/img/avatars/thumb-13.jpg",
        avatarColor: "",
      },
      {
        name: "Ella Robinson",
        img: "/img/avatars/thumb-15.jpg",
        avatarColor: "",
      },
    ],
  },
];

export default ProjectListData;
